# Generated by Django 2.1.4 on 2019-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_auto_20190127_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
