# Generated by Django 2.1.4 on 2019-01-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_hosts_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name=' Aktif edilsin mi?'),
        ),
    ]
