# Generated by Django 2.1.4 on 2019-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_auto_20190130_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_name',
            field=models.CharField(help_text='deneme', max_length=50, unique=True, verbose_name='Host Adı'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
