# Generated by Django 2.1.4 on 2019-01-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0004_auto_20190130_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.ManyToManyField(to='hosts.Hosts')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=150, verbose_name='Servis Açıklaması')),
                ('check_command', models.CharField(max_length=150, verbose_name='Komut')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceTemplate'),
        ),
    ]
