# Generated by Django 2.1.4 on 2019-02-05 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_command_desc', models.CharField(help_text='Türkçe karakter kullanmayınız. Harf, sayı, boşluk, tire (-) ve iki nokta üstüste (:) içerebilir.', max_length=150, unique=True, verbose_name='Servis Komut Açıklaması')),
                ('service_check_command', models.CharField(max_length=150, verbose_name='Servis Komutu')),
            ],
        ),
        migrations.AddField(
            model_name='services',
            name='service_description',
            field=models.CharField(default=django.utils.timezone.now, help_text='Türkçe karakter kullanmayınız. Harf, sayı, boşluk, tire (-) ve iki nokta üstüste (:) içerebilir.', max_length=150, verbose_name='Servis Açıklaması'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceCommand'),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='check_command',
            field=models.CharField(max_length=150, verbose_name='Servis Komutu'),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='service_description',
            field=models.CharField(help_text='Türkçe karakter kullanmayınız. Harf, sayı, boşluk, tire (-) ve iki nokta üstüste (:) içerebilir.', max_length=150, unique=True, verbose_name='Servis Açıklaması'),
        ),
    ]
