# Generated by Django 2.1.4 on 2019-02-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190206_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecommand',
            old_name='service_check_command',
            new_name='check_command',
        ),
        migrations.RenameField(
            model_name='servicecommand',
            old_name='service_command_desc',
            new_name='command_description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='template',
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceCommand'),
        ),
    ]
