# Generated by Django 2.1.4 on 2019-02-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190206_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceTemplate',
        ),
    ]
