# Generated by Django 2.1.4 on 2018-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostgroup_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=150)),
            ],
        ),
    ]
