# Generated by Django 2.1.4 on 2019-01-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50, verbose_name='Host Adı')),
                ('alias', models.CharField(max_length=150, verbose_name='Host Açıklaması')),
                ('address', models.GenericIPAddressField(verbose_name='IP Adresi')),
            ],
        ),
        migrations.AlterField(
            model_name='host_groups',
            name='alias',
            field=models.CharField(max_length=150, verbose_name='Host Grubu Açıklaması'),
        ),
        migrations.AlterField(
            model_name='host_groups',
            name='hostgroup_name',
            field=models.CharField(max_length=50, verbose_name='Host Grubu Adı'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='hostgroups',
            field=models.ManyToManyField(to='host_groups.Host_Groups', verbose_name='Host Grubu'),
        ),
    ]
