# Generated by Django 2.1.4 on 2019-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_groups', '0003_auto_20190124_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_groups',
            name='hostgroup_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Host Grubu Adı'),
        ),
    ]
